-- Refuse the sites that two surveys on 2026-09-26 could not use:
--
-- * the source survey (docs/source-survey-2026-09.md, issue #47), made with
--   the old ThaleiaBot UA. Its REFUSED table also lists CreativeMornings
--   London, Southbank Centre and the Hayward Gallery (southbankcentre.co.uk
--   too); migration ..08 already seeds those domains, so they are left out.
-- * the venue-discovery pass (issue #104), made with the MuseNMingleBot UA.
--   It also saw a plain 403 (no bot challenge) on guessed listing paths of
--   paradoxmuseum.com and domobaal.com; those are left out until someone
--   re-checks each with its real listing URL.
--
-- Nothing was retried with another User-Agent.
--
-- Migrations are APPEND-ONLY: never edit this file once merged.

INSERT INTO events.refused_sources (domain, name, url, reason_code, reason_text, checked_on, issue_url)
VALUES
    -- Issue #47: the 2026-09 source survey.
    ('royalacademy.org.uk', 'Royal Academy of Arts', 'https://www.royalacademy.org.uk/exhibitions-and-events',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('npg.org.uk', 'National Portrait Gallery', 'https://www.npg.org.uk/whats-on',
     'bot_blocked',
     'its what''s-on page returns a Cloudflare 403 to our bot; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('dulwichpicturegallery.org.uk', 'Dulwich Picture Gallery', 'https://www.dulwichpicturegallery.org.uk/whats-on/',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('thersa.org', 'RSA (Royal Society of Arts)', 'https://www.thersa.org/events',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('frieze.com', 'Frieze London / Masters', 'https://www.frieze.com/fairs/frieze-london',
     'bot_blocked',
     'its site returns a Cloudflare 403 to our bot; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('photolondon.org', 'Photo London', 'https://www.photolondon.org/',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('craftscouncil.org.uk', 'Crafts Council / Collect', 'https://www.craftscouncil.org.uk/whats-on',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('londonist.com', 'Londonist', 'https://londonist.com/things-to-do',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('visitlondon.com', 'Visit London', 'https://www.visitlondon.com/things-to-do/whats-on/art-and-exhibitions',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('theschooloflife.com', 'The School of Life (London)', 'https://www.theschooloflife.com/london/',
     'bot_blocked',
     'its site answers our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('societyofauthors.org', 'Society of Authors', 'https://societyofauthors.org/events/',
     'bot_blocked',
     'its site returns a Cloudflare 403 to our bot; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('hauserwirth.com', 'Hauser & Wirth', 'https://www.hauserwirth.com/hauser-wirth-exhibitions/',
     'bot_blocked',
     'its site answers our bot''s first request, even for robots.txt, with 429 Too Many Requests; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('poetrysociety.org.uk', 'Poetry Society / Poetry Café', 'https://poetrysociety.org.uk/events/',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('gresham.ac.uk', 'Gresham College', 'https://www.gresham.ac.uk/whats-on',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('royalsociety.org', 'Royal Society', 'https://royalsociety.org/science-events-and-lectures/',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('kingsplace.co.uk', 'Kings Place', 'https://www.kingsplace.co.uk/whats-on/',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('foyles.co.uk', 'Foyles', 'https://www.foyles.co.uk/events',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('buildingcentre.co.uk', 'Building Centre', 'https://www.buildingcentre.co.uk/whats-on',
     'bot_blocked',
     'its site returns 403 to our bot, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('ltmuseum.co.uk', 'London Transport Museum', 'https://www.ltmuseum.co.uk/whats-on',
     'bot_blocked',
     'its what''s-on page answers our bot with a Cloudflare block page (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('britishmuseum.org', 'British Museum', 'https://www.britishmuseum.org/exhibitions-events',
     'bot_blocked',
     'its exhibition pages answer our bot with a Cloudflare challenge (403); we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('eventbrite.co.uk', 'Eventbrite', 'https://www.eventbrite.co.uk/d/united-kingdom--london/arts/',
     'terms',
     'its terms of service forbid scraping, crawling and automated extraction, and its public '
     || 'event-search API was removed around 2020',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('meetup.com', 'Meetup', 'https://www.meetup.com/find/',
     'terms',
     'its terms forbid scraping, and its API needs a paid Meetup Pro subscription',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('timeout.com', 'Time Out London', 'https://www.timeout.com/london/art',
     'no_event_data',
     'its pages are editorial lists with no structured event data',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('dice.fm', 'DICE', 'https://dice.fm/browse/london',
     'other',
     'it sells music and nightlife tickets, which are out of scope, and its listings only '
     || 'render with JavaScript',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('londondesignfestival.com', 'London Design Festival', 'https://www.londondesignfestival.com/events',
     'js_only',
     'its events only render with JavaScript; the page itself just says "Loading…"',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('makerversity.org', 'Makerversity', 'https://makerversity.org/',
     'js_only',
     'its site only renders with JavaScript and we found no public events listing',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('londonwriterssalon.com', 'London Writers'' Salon', 'https://londonwriterssalon.com/',
     'other',
     'its events are behind a community login and mostly online',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),
    ('artnight.london', 'Art Night', 'https://artnight.london/',
     'other',
     'its TLS certificate didn''t match its domain, so the site couldn''t be reached securely',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/47'),

    -- Issue #104: the 2026-09-26 venue-discovery pass.
    ('nationaltheatre.org.uk', 'National Theatre', 'https://www.nationaltheatre.org.uk/whats-on/',
     'bot_blocked',
     'its site returns 403 to the MuseNMingleBot User-Agent, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('rct.uk', 'The King''s Gallery (Royal Collection Trust)', 'https://www.rct.uk/visit/the-kings-gallery-buckingham-palace',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a 403 bot challenge, even for robots.txt; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('jewishmuseum.org.uk', 'Jewish Museum London', 'https://jewishmuseum.org.uk/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403), even for '
     || 'robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('postalmuseum.org', 'The Postal Museum', 'https://www.postalmuseum.org/whats-on/',
     'bot_blocked',
     'its what''s-on page answers the MuseNMingleBot User-Agent with a 403 bot challenge; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('bowstreetmuseum.org.uk', 'Bow Street Police Museum', 'https://bowstreetmuseum.org.uk/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403), even for '
     || 'robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('mocomuseum.com', 'Moco Museum London', 'https://www.mocomuseum.com/london/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403); '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('delightexhibit.com', 'Delight', 'https://delightexhibit.com/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a 403 bot challenge, even for robots.txt; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('debutcontemporary.com', 'Debut Contemporary', 'https://www.debutcontemporary.com/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403), even for '
     || 'robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('stanfords.co.uk', 'Stanfords', 'https://www.stanfords.co.uk/events/',
     'bot_blocked',
     'its events page answers the MuseNMingleBot User-Agent with a 403 bot challenge; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('dove-studios.com', 'Dove Studios', 'https://www.dove-studios.com/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('peterharrington.co.uk', 'Peter Harrington (rare books)', 'https://www.peterharrington.co.uk/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('bvwm.org.uk', 'British Vintage Wireless and Television Museum', 'https://bvwm.org.uk/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a 403 bot challenge, even for robots.txt; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('theclockworks.org', 'The Clockworks', 'https://theclockworks.org/',
     'bot_blocked',
     'its site returns 403 to the MuseNMingleBot User-Agent, even for robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('wimbledonmuseum.org.uk', 'Museum of Wimbledon', 'https://www.wimbledonmuseum.org.uk/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a 403 bot challenge, even for robots.txt; '
     || 'we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('kew.org', 'Kew Gardens (Marianne North Gallery)', 'https://www.kew.org/kew-gardens/whats-on',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403), even for '
     || 'robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('forbiddenplanet.com', 'Forbidden Planet', 'https://forbiddenplanet.com/',
     'bot_blocked',
     'its site answers the MuseNMingleBot User-Agent with a Cloudflare challenge (403), even for '
     || 'robots.txt; we don''t evade blocks',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('eastendwomensmuseum.org', 'East End Women''s Museum', 'https://eastendwomensmuseum.org/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('lesfetesgalantes.com', 'Les Fêtes Galantes', 'https://lesfetesgalantes.com/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('angus-hughes.org', 'Elements Gallery (Angus Hughes)', 'https://angus-hughes.org/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('eveleibegallery.com', 'Eve Leibe Gallery', 'https://www.eveleibegallery.com/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104'),
    ('hellenicbookservice.com', 'Hellenic Bookservice', 'https://www.hellenicbookservice.com/',
     'robots_disallowed',
     'its robots.txt disallows the whole site for all crawlers',
     DATE '2026-09-26', 'https://github.com/alexsiri7/musenmingle/issues/104')
ON CONFLICT (domain) DO NOTHING;
