-- Seed London galleries on the Artlogic CMS (src/sources/artlogic.rs,
-- platform 'artlogic'), daily; issue #52. One row per gallery, keyed
-- `artlogic-<gallery>`, with the post-redirect host as base_url/domain and
-- `config` holding the listing paths, the London venue(s) and, for galleries
-- with spaces elsewhere, the location labels that mark a London show. To
-- add a gallery, see "Adding an Artlogic gallery" in docs/adding-a-scraper.md.
--
-- Probed 2026-09-27 with the MuseNMingleBot UA (robots.txt, one listing page,
-- and the terms and contact pages): every host serves the same Artlogic
-- robots.txt, which allows /exhibitions/. Addresses come from each site's
-- footer or contact page.
--
-- Not seeded (see the PR for #52): Stephen Friedman (no longer on Artlogic),
-- Trinity Art Gallery (placeholder page), Marian Goodman (no London shows
-- listed), The Fine Art Society (now in Edinburgh), Hales and The Nine
-- British Art (no gallery address on the site), Gallery 1957, Hignell, the
-- Brown Collection, 8 Holland Street and Ben Uri (current lists are mostly
-- off-site, online or undated with no location labels to filter on).
--
-- Migrations are APPEND-ONLY: never edit this file once merged.

INSERT INTO events.sources (key, kind, base_url, domain, interval_minutes, enabled,
                            display_name, store_description, store_image, policy_note,
                            platform, config)
VALUES
    ('artlogic-victoria-miro', 'scraper', 'https://www.victoria-miro.com', 'www.victoria-miro.com', 1440, TRUE,
     'Victoria Miro', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Victoria Miro", "address": "16 Wharf Road, London N1 7RW"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-kate-macgarry', 'scraper', 'https://www.katemacgarry.com', 'www.katemacgarry.com', 1440, TRUE,
     'Kate MacGarry', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current-future/"], "venue": {"name": "Kate MacGarry", "address": "27 Old Nichol Street, London E2 7HR"}}'::jsonb),
    ('artlogic-frith-street', 'scraper', 'https://www.frithstreetgallery.com', 'www.frithstreetgallery.com', 1440, TRUE,
     'Frith Street Gallery', FALSE, FALSE,
     'Terms (https://www.frithstreetgallery.com/terms-and-conditions) prohibit reproduction other than under a copyright notice the site doesn''t have: facts + link only (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Frith Street Gallery", "address": "17-18 Golden Square, London W1F 9JJ"}, "locations": [{"match": "Golden Square"}, {"match": "Soho Square", "address": "60 Frith Street, London W1D 3JJ"}]}'::jsonb),
    ('artlogic-timothy-taylor', 'scraper', 'https://www.timothytaylor.com', 'www.timothytaylor.com', 1440, TRUE,
     'Timothy Taylor', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Timothy Taylor", "address": "15 Bolton Street, London W1J 8BG"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-kristin-hjellegjerde', 'scraper', 'https://kristinhjellegjerde.com', 'kristinhjellegjerde.com', 1440, TRUE,
     'Kristin Hjellegjerde Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Kristin Hjellegjerde Gallery", "address": "36 Tanner Street, London SE1 3LD"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-tiwani', 'scraper', 'https://www.tiwani.co.uk', 'www.tiwani.co.uk', 1440, TRUE,
     'Tiwani Contemporary', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Tiwani Contemporary", "address": "24 Cork Street, London W1S 3NG"}}'::jsonb),
    ('artlogic-edel-assanti', 'scraper', 'https://edelassanti.com', 'edelassanti.com', 1440, TRUE,
     'Edel Assanti', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/"], "venue": {"name": "Edel Assanti", "address": "1B Little Titchfield Street, Fitzrovia, London"}, "locations": [{"match": "Fitzrovia"}, {"match": "Little Titchfield"}, {"match": "St James", "address": "11 Bury Street, St James''s, London"}]}'::jsonb),
    ('artlogic-richard-saltoun', 'scraper', 'https://www.richardsaltoun.com', 'www.richardsaltoun.com', 1440, TRUE,
     'Richard Saltoun Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current-forthcoming/"], "venue": {"name": "Richard Saltoun Gallery", "address": "41 Dover Street, London W1S 4NS"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-amanda-wilkinson', 'scraper', 'https://amandawilkinsongallery.com', 'amandawilkinsongallery.com', 1440, TRUE,
     'Amanda Wilkinson', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/location/1/"], "venue": {"name": "Amanda Wilkinson", "address": "1st Floor, 47 Farringdon Road, London EC1M 3JB"}}'::jsonb),
    ('artlogic-annely-juda', 'scraper', 'https://www.annelyjudafineart.co.uk', 'www.annelyjudafineart.co.uk', 1440, TRUE,
     'Annely Juda Fine Art', TRUE, FALSE,
     'Its only terms (https://www.annelyjudafineart.co.uk/terms-and-conditions/) are terms of sale, which say images made for selling works may be used only with the gallery''s permission: no images, descriptions kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/"], "venue": {"name": "Annely Juda Fine Art", "address": "16 Hanover Square, London W1S 1HT"}}'::jsonb),
    ('artlogic-flowers', 'scraper', 'https://www.flowersgallery.com', 'www.flowersgallery.com', 1440, TRUE,
     'Flowers Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Flowers Gallery", "address": "21 Cork Street, London W1S 3LZ"}, "locations": [{"match": "Cork Street"}, {"match": "Kingsland", "address": "82 Kingsland Road, London E2 8DP"}]}'::jsonb),
    ('artlogic-grimm', 'scraper', 'https://grimmgallery.com', 'grimmgallery.com', 1440, TRUE,
     'GRIMM', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "GRIMM", "address": "43a Duke Street, St James''s, London SW1Y 6DD"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-sunday-painter', 'scraper', 'https://thesundaypainter.co.uk', 'thesundaypainter.co.uk', 1440, TRUE,
     'The Sunday Painter', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "The Sunday Painter", "address": "117-119 South Lambeth Road, London SW8 1XA"}}'::jsonb),
    ('artlogic-cristea-roberts', 'scraper', 'https://cristearoberts.com', 'cristearoberts.com', 1440, TRUE,
     'Cristea Roberts Gallery', TRUE, FALSE,
     'Its only terms (https://cristearoberts.com/legal/) are terms of sale, which say images made for selling works may be used only with the gallery''s permission: no images, descriptions kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Cristea Roberts Gallery", "address": "43 Pall Mall, London SW1Y 5JG"}}'::jsonb),
    ('artlogic-gazelli', 'scraper', 'https://gazelliarthouse.com', 'gazelliarthouse.com', 1440, TRUE,
     'Gazelli Art House', TRUE, TRUE,
     'Its only terms (https://gazelliarthouse.com/terms-and-conditions/) are terms of sale and don''t restrict listings, so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current-forthcoming/"], "venue": {"name": "Gazelli Art House", "address": "39 Dover Street, London W1S 4NN"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-waddington-custot', 'scraper', 'https://www.waddingtoncustot.com', 'www.waddingtoncustot.com', 1440, TRUE,
     'Waddington Custot', FALSE, FALSE,
     'Terms (https://www.waddingtoncustot.com/terms-and-conditions/) prohibit reproduction or republication of site materials without permission: facts + link only (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current-forthcoming/"], "venue": {"name": "Waddington Custot", "address": "11 Cork Street, London W1S 3LT"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-ropac', 'scraper', 'https://ropac.net', 'ropac.net', 1440, TRUE,
     'Thaddaeus Ropac', TRUE, TRUE,
     'Its only terms (https://ropac.net/terms-and-conditions/) are terms of sale and don''t restrict listings, so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Thaddaeus Ropac, Ely House", "address": "37 Dover Street, London W1S 4NJ"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-pilar-corrias', 'scraper', 'https://www.pilarcorrias.com', 'www.pilarcorrias.com', 1440, TRUE,
     'Pilar Corrias', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Pilar Corrias", "address": "51 Conduit Street, London W1S 2YT"}, "locations": [{"match": "Conduit Street"}, {"match": "Savile Row", "address": "2 Savile Row, London W1S 3PA"}], "unlabelled_at_venue": true}'::jsonb),
    ('artlogic-larkin-durey', 'scraper', 'https://www.larkindurey.com', 'www.larkindurey.com', 1440, TRUE,
     'Larkin Durey', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Larkin Durey", "address": "13 Mason''s Yard, London SW1Y 6BU"}}'::jsonb),
    ('artlogic-jacobson', 'scraper', 'https://www.jacobsongallery.com', 'www.jacobsongallery.com', 1440, TRUE,
     'Bernard Jacobson Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/"], "venue": {"name": "Bernard Jacobson Gallery", "address": "8 Golden Square, London W1F 9HY"}}'::jsonb),
    ('artlogic-hope-93', 'scraper', 'https://hope93.com', 'hope93.com', 1440, TRUE,
     'Hope 93', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Hope 93", "address": "54 Eastcastle Street, London W1W 8EF"}}'::jsonb),
    ('artlogic-eclectic', 'scraper', 'https://eclecticgallery.co.uk', 'eclecticgallery.co.uk', 1440, TRUE,
     'Eclectic Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Eclectic Gallery", "address": "16 Newman Street, London W1T 1PB"}}'::jsonb),
    ('artlogic-pontone', 'scraper', 'https://pontonegallery.com', 'pontonegallery.com', 1440, TRUE,
     'Pontone Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Pontone Gallery", "address": "74 Newman Street, London W1T 3DB"}}'::jsonb),
    ('artlogic-ben-brown', 'scraper', 'https://www.benbrownfinearts.com', 'www.benbrownfinearts.com', 1440, TRUE,
     'Ben Brown Fine Arts', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Ben Brown Fine Arts", "address": "12 Brook''s Mews, London W1K 4DG"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-charles-burnand', 'scraper', 'https://charlesburnand.com', 'charlesburnand.com', 1440, TRUE,
     'Charles Burnand Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Charles Burnand Gallery", "address": "20 Bruton Place, London W1J 6LY"}}'::jsonb),
    ('artlogic-bankside', 'scraper', 'https://www.banksidegallery.com', 'www.banksidegallery.com', 1440, TRUE,
     'Bankside Gallery', TRUE, TRUE,
     'Its copyright notice (https://www.banksidegallery.com/copyright-notice/) asserts copyright but doesn''t restrict listings, so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/", "/exhibitions/forthcoming/"], "venue": {"name": "Bankside Gallery", "address": "48 Hopton Street, London SE1 9JH"}}'::jsonb),
    ('artlogic-jaggedart', 'scraper', 'https://www.jaggedart.com', 'www.jaggedart.com', 1440, TRUE,
     'jaggedart', TRUE, TRUE,
     'Its terms (https://www.jaggedart.com/terms-and-conditions/) only cover anti-money-laundering checks on sales and don''t restrict listings, so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/", "/exhibitions/forthcoming/"], "venue": {"name": "jaggedart", "address": "28a Devonshire Street, London W1G 6PS"}}'::jsonb),
    ('artlogic-dellasposa', 'scraper', 'https://www.dellasposa.com', 'www.dellasposa.com', 1440, TRUE,
     'Dellasposa', TRUE, TRUE,
     'Its only terms (https://www.dellasposa.com/terms-and-conditions-of-business/) are terms of sale and don''t restrict listings, so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"listing_paths": ["/exhibitions/current/", "/exhibitions/forthcoming/"], "venue": {"name": "Dellasposa", "address": "Phillimore Walk, Kensington, London W8 7SA"}}'::jsonb),
    ('artlogic-gladwell-patterson', 'scraper', 'https://gladwellpatterson.com', 'gladwellpatterson.com', 1440, TRUE,
     'Gladwell & Patterson', FALSE, FALSE,
     'Terms (https://gladwellpatterson.com/terms-and-conditions/) say no material from the site may be reproduced without written consent: facts + link only (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Gladwell & Patterson", "address": "50 Burlington Arcade, London W1J 0QJ"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-hackelbury', 'scraper', 'https://hackelbury.co.uk', 'hackelbury.co.uk', 1440, TRUE,
     'HackelBury Fine Art', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "HackelBury Fine Art", "address": "4 Launceston Place, London W8 5RL"}}'::jsonb),
    ('artlogic-jonathan-cooper', 'scraper', 'https://www.jonathancooper.co.uk', 'www.jonathancooper.co.uk', 1440, TRUE,
     'Jonathan Cooper', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Jonathan Cooper", "address": "20 Park Walk, London SW10 0AQ"}}'::jsonb),
    ('artlogic-cricket-fine-art', 'scraper', 'https://www.cricketfineart.co.uk', 'www.cricketfineart.co.uk', 1440, TRUE,
     'Cricket Fine Art', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Cricket Fine Art", "address": "2 Park Walk, Chelsea, London SW10 0AD"}}'::jsonb),
    ('artlogic-thompsons', 'scraper', 'https://www.thompsonsgallery.co.uk', 'www.thompsonsgallery.co.uk', 1440, TRUE,
     'Thompson''s Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Thompson''s Gallery", "address": "3 Seymour Place, London W1H 5AZ"}, "locations": [{"match": "London"}]}'::jsonb),
    ('artlogic-portland', 'scraper', 'https://portlandgallery.com', 'portlandgallery.com', 1440, TRUE,
     'Portland Gallery', TRUE, FALSE,
     'No terms page (/terms-and-conditions/ is a 404), but the site footer withholds consent to reproduce any images: no images, descriptions kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Portland Gallery", "address": "3 Bennet Street, London SW1A 1RP"}}'::jsonb),
    ('artlogic-mayor', 'scraper', 'https://www.mayorgallery.com', 'www.mayorgallery.com', 1440, TRUE,
     'The Mayor Gallery', TRUE, FALSE,
     'Its only terms (https://www.mayorgallery.com/terms-and-conditions/) are terms of sale, which say images made for selling works may be used only with the gallery''s permission: no images, descriptions kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "The Mayor Gallery", "address": "9 Bury Street, St James''s, London SW1Y 6AB"}}'::jsonb),
    ('artlogic-temple', 'scraper', 'https://www.templegallery.com', 'www.templegallery.com', 1440, TRUE,
     'The Temple Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "The Temple Gallery", "address": "6 Clarendon Cross, London W11 4AP"}}'::jsonb),
    ('artlogic-piano-nobile', 'scraper', 'https://www.piano-nobile.com', 'www.piano-nobile.com', 1440, TRUE,
     'Piano Nobile', TRUE, FALSE,
     'Its only terms (https://www.piano-nobile.com/terms-and-conditions/) are terms of sale, which say images made for selling works may be used only with the gallery''s permission: no images, descriptions kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "Piano Nobile", "address": "96 & 129 Portland Road, London W11 4LW"}}'::jsonb),
    ('artlogic-155a', 'scraper', 'https://155agallery.com', '155agallery.com', 1440, TRUE,
     '155A Gallery', TRUE, TRUE,
     'No terms of use on the site (none linked; /terms-and-conditions/ is a 404), so descriptions and images are kept (checked 2026-09-27)',
     'artlogic',
     '{"venue": {"name": "155A Gallery", "address": "155A Lordship Lane, East Dulwich, London SE22 8HX"}}'::jsonb)
ON CONFLICT (key) DO NOTHING;
